name: heap_analytics
description: Heap Analytics
version: 0.1.2
author: Kurt Inge Smådal <kurtinge@gmail.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
